def generate_label(attribution: str) -> str:
    if attribution == "likely_ai":
        return (
            "Provenance Guard found strong signals that this content may have been "
            "AI-generated. This label is based on automated analysis and may be "
            "appealed by the creator."
        )

    if attribution == "likely_human":
        return (
            "Provenance Guard found strong signals that this content was likely "
            "written by a human. This label is based on automated analysis and "
            "should not be treated as absolute proof."
        )

    return (
        "Provenance Guard could not confidently determine whether this content "
        "was written by a human or generated by AI. Readers should interpret "
        "this result as uncertain."
    )